const movies =[
    {
        
        "id": 1,
        "title": "Nyckeln till frihet",
        "year": "1994",
        "genres": [
            "Crime",
            "Drama"
        ],
        "ratings": [
            8,
            8,
            6,
            10,
            2,
            3,
            4,
            5,
            4,
            9,
            3,
            9,
            6,
            10,
            4,
            8,
            10,
            1,
            2,
            8,
            1,
            9,
            5,
            4,
            4,
            2,
            4,
            6,
            9,
            10
        ],
        "poster": "MV5BODU4MjU4NjIwNl5BMl5BanBnXkFtZTgwMDU2MjEyMDE@._V1_SY500_CR0,0,336,500_AL_.jpg",
        "contentRating": "15",
        "duration": "PT142M",
        "releaseDate": "1995-03-03",
        "averageRating": 0,
        "originalTitle": "The Shawshank Redemption",
        "storyline": "Chronicles the experiences of a formerly successful banker as a prisoner in the gloomy jailhouse of Shawshank after being found guilty of a crime he did not commit. The film portrays the man's unique way of dealing with his new, torturous life; along the way he befriends a number of fellow prisoners, most notably a wise long-term inmate named Red.                Written by\nJ-S-Golden",
        "actors": [
            "Tim Robbins",
            "Morgan Freeman",
            "Bob Gunton"
        ],
        "imdbRating": 9.3,
        "posterurl": "https://images-na.ssl-images-amazon.com/images/M/MV5BODU4MjU4NjIwNl5BMl5BanBnXkFtZTgwMDU2MjEyMDE@._V1_SY500_CR0,0,336,500_AL_.jpg",
        "isRated": false
    },
    {
        "id": 2,
        "title": "Gudfadern",
        "year": "1972",
        "genres": [
            "Crime",
            "Drama"
        ],
        "ratings": [
            6,
            10,
            4,
            10,
            1,
            3,
            7,
            2,
            3,
            3,
            3,
            4,
            2,
            5,
            6,
            9,
            10,
            8,
            7,
            4,
            8,
            9,
            9,
            10,
            4,
            6,
            2,
            9,
            7,
            7
        ],
        "poster": "MV5BZTRmNjQ1ZDYtNDgzMy00OGE0LWE4N2YtNTkzNWQ5ZDhlNGJmL2ltYWdlL2ltYWdlXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_SY500_CR0,0,352,500_AL_.jpg",
        "contentRating": "15",
        "duration": "PT175M",
        "releaseDate": "1972-09-27",
        "averageRating": 0,
        "originalTitle": "The Godfather",
        "storyline": "When the aging head of a famous crime family decides to transfer his position to one of his subalterns, a series of unfortunate events start happening to the family, and a war begins between all the well-known families leading to insolence, deportation, murder and revenge, and ends with the favorable successor being finally chosen.                Written by\nJ. S. Golden",
        "actors": [
            "Marlon Brando",
            "Al Pacino",
            "James Caan"
        ],
        "imdbRating": 9.2,
        "posterurl": "https://images-na.ssl-images-amazon.com/images/M/MV5BZTRmNjQ1ZDYtNDgzMy00OGE0LWE4N2YtNTkzNWQ5ZDhlNGJmL2ltYWdlL2ltYWdlXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_SY500_CR0,0,352,500_AL_.jpg",
        "isRated": false
    },
    {
        "id": 3,
        "title": "Gudfadern del II",
        "year": "1974",
        "genres": [
            "Crime",
            "Drama"
        ],
        "ratings": [
            2,
            5,
            1,
            1,
            8,
            4,
            2,
            3,
            10,
            10,
            4,
            9,
            8,
            9,
            7,
            6,
            6,
            9,
            9,
            4,
            1,
            8,
            4,
            5,
            7,
            7,
            7,
            1,
            10,
            6
        ],
        "poster": "MV5BMjZiNzIxNTQtNDc5Zi00YWY1LThkMTctMDgzYjY4YjI1YmQyL2ltYWdlL2ltYWdlXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_SY500_CR0,0,351,500_AL_.jpg",
        "contentRating": "15",
        "duration": "PT202M",
        "releaseDate": "1975-07-28",
        "averageRating": 0,
        "originalTitle": "The Godfather: Part II",
        "storyline": "The continuing saga of the Corleone crime family tells the story of a young Vito Corleone growing up in Sicily and in 1910s New York; and follows Michael Corleone in the 1950s as he attempts to expand the family business into Las Vegas, Hollywood and Cuba.                Written by\nKeith Loh <loh@sfu.ca>",
        "actors": [
            "Al Pacino",
            "Robert De Niro",
            "Robert Duvall"
        ],
        "imdbRating": 9.0,
        "posterurl": "https://images-na.ssl-images-amazon.com/images/M/MV5BMjZiNzIxNTQtNDc5Zi00YWY1LThkMTctMDgzYjY4YjI1YmQyL2ltYWdlL2ltYWdlXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_SY500_CR0,0,351,500_AL_.jpg",
        "isRated": false
    },
    {
        "id": 4,
        "title": "The Dark Knight",
        "year": "2008",
        "genres": [
            "Action",
            "Crime",
            "Drama"
        ],
        "ratings": [
            3,
            6,
            4,
            1,
            6,
            10,
            6,
            3,
            5,
            9,
            1,
            3,
            1,
            7,
            8,
            10,
            6,
            2,
            8,
            6,
            7,
            1,
            4,
            3,
            8,
            3,
            10,
            8,
            10,
            4
        ],
        "poster": "MV5BMTMxNTMwODM0NF5BMl5BanBnXkFtZTcwODAyMTk2Mw@@._V1_SY500_CR0,0,337,500_AL_.jpg",
        "contentRating": "15",
        "duration": "PT152M",
        "releaseDate": "2008-07-25",
        "averageRating": 0,
        "originalTitle": "",
        "storyline": "Set within a year after the events of Batman Begins, Batman, Lieutenant James Gordon, and new district attorney Harvey Dent successfully begin to round up the criminals that plague Gotham City until a mysterious and sadistic criminal mastermind known only as the Joker appears in Gotham, creating a new wave of chaos. Batman's struggle against the Joker becomes deeply personal, forcing him to \"confront everything he believes\" and improve his technology to stop him. A love triangle develops between Bruce Wayne, Dent and Rachel Dawes.                Written by\nLeon Lombardi",
        "actors": [
            "Christian Bale",
            "Heath Ledger",
            "Aaron Eckhart"
        ],
        "imdbRating": 9.0,
        "posterurl": "https://images-na.ssl-images-amazon.com/images/M/MV5BMTMxNTMwODM0NF5BMl5BanBnXkFtZTcwODAyMTk2Mw@@._V1_SY500_CR0,0,337,500_AL_.jpg",
        "isRated": false
    },
    {
        "id": 5,
        "title": "12 edsvurna m\u00e4n",
        "year": "1957",
        "genres": [
            "Crime",
            "Drama"
        ],
        "ratings": [
            3,
            5,
            3,
            3,
            10,
            3,
            4,
            1,
            6,
            10,
            2,
            8,
            4,
            6,
            8,
            6,
            1,
            10,
            4,
            5,
            9,
            3,
            2,
            4,
            8,
            10,
            10,
            7,
            9,
            6
        ],
        "poster": "MV5BODQwOTc5MDM2N15BMl5BanBnXkFtZTcwODQxNTEzNA@@._V1_SY500_CR0,0,333,500_AL_.jpg",
        "contentRating": "15",
        "duration": "PT96M",
        "releaseDate": "1957-07-29",
        "averageRating": 0,
        "originalTitle": "12 Angry Men",
        "storyline": "The defense and the prosecution have rested and the jury is filing into the jury room to decide if a young man is guilty or innocent of murdering his father. What begins as an open-and-shut case of murder soon becomes a detective story that presents a succession of clues creating doubt, and a mini-drama of each of the jurors' prejudices and preconceptions about the trial, the accused, and each other. Based on the play, all of the action takes place on the stage of the jury room.                Written by\npjk <PETESID@VNET.IBM.COM>",
        "actors": [
            "Henry Fonda",
            "Lee J. Cobb",
            "Martin Balsam"
        ],
        "imdbRating": 8.9,
        "posterurl": "https://images-na.ssl-images-amazon.com/images/M/MV5BODQwOTc5MDM2N15BMl5BanBnXkFtZTcwODQxNTEzNA@@._V1_SY500_CR0,0,333,500_AL_.jpg",
        "isRated": false
    },
    {
        "id": 6,
        "title": "Schindler's List",
        "year": "1993",
        "genres": [
            "Biography",
            "Drama",
            "History"
        ],
        "ratings": [
            2,
            6,
            7,
            8,
            8,
            6,
            2,
            4,
            6,
            2,
            3,
            3,
            5,
            9,
            5,
            10,
            9,
            5,
            5,
            2,
            10,
            4,
            8,
            7,
            4,
            10,
            2,
            10,
            4,
            10
        ],
        "poster": "MV5BNDE4OTMxMTctNmRhYy00NWE2LTg3YzItYTk3M2UwOTU5Njg4XkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_SY500_CR0,0,333,500_AL_.jpg",
        "contentRating": "15",
        "duration": "PT195M",
        "releaseDate": "1994-03-04",
        "averageRating": 0,
        "originalTitle": "",
        "storyline": "Oskar Schindler is a vainglorious and greedy German businessman who becomes an unlikely humanitarian amid the barbaric German Nazi reign when he feels compelled to turn his factory into a refuge for Jews. Based on the true story of Oskar Schindler who managed to save about 1100 Jews from being gassed at the Auschwitz concentration camp, it is a testament to the good in all of us.                Written by\nHarald Mayr <marvin@bike.augusta.de>",
        "actors": [
            "Liam Neeson",
            "Ralph Fiennes",
            "Ben Kingsley"
        ],
        "imdbRating": 8.9,
        "posterurl": "https://images-na.ssl-images-amazon.com/images/M/MV5BNDE4OTMxMTctNmRhYy00NWE2LTg3YzItYTk3M2UwOTU5Njg4XkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_SY500_CR0,0,333,500_AL_.jpg",
        "isRated": false
    },
    {
        "id": 7,
        "title": "Pulp Fiction",
        "year": "1994",
        "genres": [
            "Crime",
            "Drama"
        ],
        "ratings": [
            2,
            9,
            7,
            7,
            7,
            2,
            2,
            4,
            1,
            9,
            6,
            3,
            4,
            10,
            8,
            6,
            7,
            5,
            9,
            4,
            3,
            5,
            9,
            3,
            8,
            2,
            6,
            7,
            4,
            4
        ],
        "poster": "MV5BMTkxMTA5OTAzMl5BMl5BanBnXkFtZTgwNjA5MDc3NjE@._V1_SY500_CR0,0,336,500_AL_.jpg",
        "contentRating": "15",
        "duration": "PT154M",
        "releaseDate": "1994-11-25",
        "averageRating": 0,
        "originalTitle": "",
        "storyline": "Jules Winnfield (Samuel L. Jackson) and Vincent Vega (John Travolta) are two hit men who are out to retrieve a suitcase stolen from their employer, mob boss Marsellus Wallace (Ving Rhames). Wallace has also asked Vincent to take his wife Mia (Uma Thurman) out a few days later when Wallace himself will be out of town. Butch Coolidge (Bruce Willis) is an aging boxer who is paid by Wallace to lose his weight. The lives of these seemingly unrelated people are woven together comprising of a series of funny, bizarre and uncalled-for incidents.                Written by\nSoumitra",
        "actors": [
            "John Travolta",
            "Uma Thurman",
            "Samuel L. Jackson"
        ],
        "imdbRating": 8.9,
        "posterurl": "https://images-na.ssl-images-amazon.com/images/M/MV5BMTkxMTA5OTAzMl5BMl5BanBnXkFtZTgwNjA5MDc3NjE@._V1_SY500_CR0,0,336,500_AL_.jpg",
        "isRated": false
    },
    {
        "id": 8,
        "title": "Sagan om konungens \u00e5terkomst",
        "year": "2003",
        "genres": [
            "Adventure",
            "Drama",
            "Fantasy"
        ],
        "ratings": [
            6,
            3,
            2,
            7,
            5,
            2,
            10,
            10,
            4,
            5,
            7,
            1,
            8,
            4,
            8,
            7,
            2,
            8,
            5,
            5,
            6,
            3,
            3,
            10,
            10,
            2,
            1,
            8,
            3,
            5
        ],
        "poster": "MV5BYWY1ZWQ5YjMtMDE0MS00NWIzLWE1M2YtODYzYTk2OTNlYWZmXkEyXkFqcGdeQXVyNDUyOTg3Njg@._V1_SY500_SX334_AL_.jpg",
        "contentRating": "11",
        "duration": "PT201M",
        "releaseDate": "2003-12-17",
        "averageRating": 0,
        "originalTitle": "The Lord of the Rings: The Return of the King",
        "storyline": "The final confrontation between the forces of good and evil fighting for control of the future of Middle-earth. Hobbits Frodo and Sam reach Mordor in their quest to destroy the \"one ring\", while Aragorn leads the forces of good against Sauron's evil army at the stone city of Minas Tirith.                Written by\nJwelch5742",
        "actors": [
            "Elijah Wood",
            "Viggo Mortensen",
            "Ian McKellen"
        ],
        "imdbRating": 8.9,
        "posterurl": "https://images-na.ssl-images-amazon.com/images/M/MV5BYWY1ZWQ5YjMtMDE0MS00NWIzLWE1M2YtODYzYTk2OTNlYWZmXkEyXkFqcGdeQXVyNDUyOTg3Njg@._V1_SY500_SX334_AL_.jpg",
        "isRated": false
    },
    {
        "id": 9,
        "title": "Den gode, den onde, den fule",
        "year": "1966",
        "genres": [
            "Western"
        ],
        "ratings": [
            2,
            7,
            2,
            2,
            3,
            2,
            4,
            7,
            10,
            7,
            7,
            7,
            2,
            3,
            8,
            8,
            6,
            3,
            6,
            4,
            8,
            7,
            9,
            1,
            10,
            2,
            4,
            10,
            3,
            8
        ],
        "poster": "MV5BOTQ5NDI3MTI4MF5BMl5BanBnXkFtZTgwNDQ4ODE5MDE@._V1_SY500_CR0,0,328,500_AL_.jpg",
        "contentRating": "",
        "duration": "PT161M",
        "releaseDate": "1968-04-10",
        "averageRating": 0,
        "originalTitle": "Il buono, il brutto, il cattivo",
        "storyline": "Blondie (The Good) is a professional gunslinger who is out trying to earn a few dollars. Angel Eyes (The Bad) is a hit man who always commits to a task and sees it through, as long as he is paid to do so. And Tuco (The Ugly) is a wanted outlaw trying to take care of his own hide. Tuco and Blondie share a partnership together making money off Tuco's bounty, but when Blondie unties the partnership, Tuco tries to hunt down Blondie. When Blondie and Tuco come across a horse carriage loaded with dead bodies, they soon learn from the only survivor (Bill Carson) that he and a few other men have buried a stash of gold in a cemetery. Unfortunately Carson dies and Tuco only finds out the name of the cemetery, while Blondie finds out the name on the grave. Now the two must keep each other alive in order to find the gold. Angel Eyes (who had been looking for Bill Carson) discovers that Tuco and Blondie met with Carson and knows they know the location of the gold. All he needs is for the two to ...                Written by\nJeremy Thomson",
        "actors": [
            "Clint Eastwood",
            "Eli Wallach",
            "Lee Van Cleef"
        ],
        "imdbRating": 8.9,
        "posterurl": "https://images-na.ssl-images-amazon.com/images/M/MV5BOTQ5NDI3MTI4MF5BMl5BanBnXkFtZTgwNDQ4ODE5MDE@._V1_SY500_CR0,0,328,500_AL_.jpg",
        "isRated": false
    },
    {
        "id": 10,
        "title": "Fight Club",
        "year": "1999",
        "genres": [
            "Drama"
        ],
        "ratings": [
            6,
            5,
            10,
            10,
            6,
            6,
            6,
            7,
            2,
            8,
            10,
            2,
            3,
            5,
            1,
            3,
            10,
            3,
            6,
            2,
            6,
            2,
            10,
            4,
            4,
            8,
            9,
            10,
            10,
            5
        ],
        "poster": "MV5BZGY5Y2RjMmItNDg5Yy00NjUwLThjMTEtNDc2OGUzNTBiYmM1XkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_SX290_CR0,0,290,429_AL_.jpg",
        "contentRating": "15",
        "duration": "PT139M",
        "releaseDate": "1999-12-25",
        "averageRating": 0,
        "originalTitle": "",
        "storyline": "A nameless first person narrator (Edward Norton) attends support groups in attempt to subdue his emotional state and relieve his insomniac state. When he meets Marla (Helena Bonham Carter), another fake attendee of support groups, his life seems to become a little more bearable. However when he associates himself with Tyler (Brad Pitt) he is dragged into an underground fight club and soap making scheme. Together the two men spiral out of control and engage in competitive rivalry for love and power. When the narrator is exposed to the hidden agenda of Tyler's fight club, he must accept the awful truth that Tyler may not be who he says he is.                Written by\nRhiannon",
        "actors": [
            "Brad Pitt",
            "Edward Norton",
            "Meat Loaf"
        ],
        "imdbRating": 8.8,
        "posterurl": "https://images-na.ssl-images-amazon.com/images/M/MV5BZGY5Y2RjMmItNDg5Yy00NjUwLThjMTEtNDc2OGUzNTBiYmM1XkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_SX290_CR0,0,290,429_AL_.jpg",
        "isRated": false
    },
    {
        "id": 11,
        "title": "Sagan om ringen: H\u00e4rskarringen",
        "year": "2001",
        "genres": [
            "Adventure",
            "Drama",
            "Fantasy"
        ],
        "ratings": [
            1,
            2,
            4,
            3,
            2,
            4,
            7,
            5,
            9,
            3,
            5,
            1,
            10,
            4,
            2,
            2,
            10,
            7,
            5,
            9,
            10,
            4,
            3,
            5,
            8,
            3,
            2,
            5,
            5,
            4
        ],
        "poster": "MV5BNmFmZDdkODMtNzUyMy00NzhhLWFjZmEtMGMzYjNhMDA1NTBkXkEyXkFqcGdeQXVyNDUyOTg3Njg@._V1_SY500_SX342_AL_.jpg",
        "contentRating": "11",
        "duration": "PT178M",
        "releaseDate": "2001-12-19",
        "averageRating": 0,
        "originalTitle": "The Lord of the Rings: The Fellowship of the Ring",
        "storyline": "An ancient Ring thought lost for centuries has been found, and through a strange twist in fate has been given to a small Hobbit named Frodo. When Gandalf discovers the Ring is in fact the One Ring of the Dark Lord Sauron, Frodo must make an epic quest to the Cracks of Doom in order to destroy it! However he does not go alone. He is joined by Gandalf, Legolas the elf, Gimli the Dwarf, Aragorn, Boromir and his three Hobbit friends Merry, Pippin and Samwise. Through mountains, snow, darkness, forests, rivers and plains, facing evil and danger at every corner the Fellowship of the Ring must go. Their quest to destroy the One Ring is the only hope for the end of the Dark Lords reign!                Written by\nPaul Twomey <toomsp@hotmail.com>",
        "actors": [
            "Elijah Wood",
            "Ian McKellen",
            "Orlando Bloom"
        ],
        "imdbRating": 8.8,
        "posterurl": "https://images-na.ssl-images-amazon.com/images/M/MV5BNmFmZDdkODMtNzUyMy00NzhhLWFjZmEtMGMzYjNhMDA1NTBkXkEyXkFqcGdeQXVyNDUyOTg3Njg@._V1_SY500_SX342_AL_.jpg",
        "isRated": false
    },
    {
        "id": 12,
        "title": "Rymdimperiet sl\u00e5r tillbaka",
        "year": "1980",
        "genres": [
            "Action",
            "Adventure",
            "Fantasy"
        ],
        "ratings": [
            2,
            3,
            10,
            2,
            7,
            8,
            1,
            4,
            1,
            5,
            8,
            5,
            8,
            2,
            8,
            4,
            3,
            6,
            10,
            3,
            5,
            2,
            9,
            7,
            3,
            1,
            10,
            6,
            7,
            10
        ],
        "poster": "MV5BYmViY2M2MTYtY2MzOS00YjQ1LWIzYmEtOTBiNjhlMGM0NjZjXkEyXkFqcGdeQXVyNDYyMDk5MTU@._V1_SY500_CR0,0,322,500_AL_.jpg",
        "contentRating": "15",
        "duration": "PT124M",
        "releaseDate": "1980-08-15",
        "averageRating": 0,
        "originalTitle": "Star Wars: Episode V - The Empire Strikes Back",
        "storyline": "Luke Skywalker, Han Solo, Princess Leia and Chewbacca face attack by the Imperial forces and its AT-AT walkers on the ice planet Hoth. While Han and Leia escape in the Millennium Falcon, Luke travels to Dagobah in search of Yoda. Only with the Jedi master's help will Luke survive when the dark side of the Force beckons him into the ultimate duel with Darth Vader.                Written by\nJwelch5742",
        "actors": [
            "Mark Hamill",
            "Harrison Ford",
            "Carrie Fisher"
        ],
        "imdbRating": 8.8,
        "posterurl": "https://images-na.ssl-images-amazon.com/images/M/MV5BYmViY2M2MTYtY2MzOS00YjQ1LWIzYmEtOTBiNjhlMGM0NjZjXkEyXkFqcGdeQXVyNDYyMDk5MTU@._V1_SY500_CR0,0,322,500_AL_.jpg",
        "isRated": false
    },
    {
        "id": 13,
        "title": "Forrest Gump",
        "year": "1994",
        "genres": [
            "Comedy",
            "Drama",
            "Romance"
        ],
        "ratings": [
            9,
            1,
            10,
            10,
            10,
            6,
            3,
            7,
            1,
            3,
            4,
            9,
            2,
            4,
            10,
            8,
            7,
            4,
            8,
            8,
            9,
            5,
            4,
            2,
            5,
            5,
            6,
            3,
            1,
            4
        ],
        "poster": "MV5BYThjM2MwZGMtMzg3Ny00NGRkLWE4M2EtYTBiNWMzOTY0YTI4XkEyXkFqcGdeQXVyNDYyMDk5MTU@._V1_SY500_CR0,0,378,500_AL_.jpg",
        "contentRating": "11",
        "duration": "PT142M",
        "releaseDate": "1994-10-14",
        "averageRating": 0,
        "originalTitle": "",
        "storyline": "Forrest Gump is a simple man with a low I.Q. but good intentions. He is running through childhood with his best and only friend Jenny. His 'mama' teaches him the ways of life and leaves him to choose his destiny. Forrest joins the army for service in Vietnam, finding new friends called Dan and Bubba, he wins medals, creates a famous shrimp fishing fleet, inspires people to jog, starts a ping-pong craze, creates the smiley, writes bumper stickers and songs, donates to people and meets the president several times. However, this is all irrelevant to Forrest who can only think of his childhood sweetheart Jenny Curran, who has messed up her life. Although in the end all he wants to prove is that anyone can love anyone.                Written by\naliw135",
        "actors": [
            "Tom Hanks",
            "Robin Wright",
            "Gary Sinise"
        ],
        "imdbRating": 8.8,
        "posterurl": "https://images-na.ssl-images-amazon.com/images/M/MV5BYThjM2MwZGMtMzg3Ny00NGRkLWE4M2EtYTBiNWMzOTY0YTI4XkEyXkFqcGdeQXVyNDYyMDk5MTU@._V1_SY500_CR0,0,378,500_AL_.jpg",
        "isRated": false
    },
    {
        "id": 14,
        "title": "Inception",
        "year": "2010",
        "genres": [
            "Action",
            "Adventure",
            "Sci-Fi"
        ],
        "ratings": [
            4,
            8,
            10,
            7,
            3,
            3,
            1,
            6,
            4,
            4,
            6,
            1,
            5,
            7,
            4,
            5,
            2,
            1,
            2,
            2,
            2,
            6,
            10,
            8,
            5,
            6,
            1,
            4,
            1,
            5
        ],
        "poster": "MV5BMjAxMzY3NjcxNF5BMl5BanBnXkFtZTcwNTI5OTM0Mw@@._V1_SY500_CR0,0,337,500_AL_.jpg",
        "contentRating": "15",
        "duration": "PT148M",
        "releaseDate": "2010-07-23",
        "averageRating": 0,
        "originalTitle": "",
        "storyline": "Dom Cobb is a skilled thief, the absolute best in the dangerous art of extraction, stealing valuable secrets from deep within the subconscious during the dream state, when the mind is at its most vulnerable. Cobb's rare ability has made him a coveted player in this treacherous new world of corporate espionage, but it has also made him an international fugitive and cost him everything he has ever loved. Now Cobb is being offered a chance at redemption. One last job could give him his life back but only if he can accomplish the impossible - inception. Instead of the perfect heist, Cobb and his team of specialists have to pull off the reverse: their task is not to steal an idea but to plant one. If they succeed, it could be the perfect crime. But no amount of careful planning or expertise can prepare the team for the dangerous enemy that seems to predict their every move. An enemy that only Cobb could have seen coming.                Written by\nWarner Bros. Pictures",
        "actors": [
            "Leonardo DiCaprio",
            "Joseph Gordon-Levitt",
            "Ellen Page"
        ],
        "imdbRating": 8.8,
        "posterurl": "https://images-na.ssl-images-amazon.com/images/M/MV5BMjAxMzY3NjcxNF5BMl5BanBnXkFtZTcwNTI5OTM0Mw@@._V1_SY500_CR0,0,337,500_AL_.jpg",
        "isRated": false
    },
    {
        "id": 15,
        "title": "Sagan om de tv\u00e5 tornen",
        "year": "2002",
        "genres": [
            "Adventure",
            "Drama",
            "Fantasy"
        ],
        "ratings": [
            8,
            2,
            2,
            3,
            10,
            9,
            1,
            8,
            4,
            7,
            1,
            7,
            5,
            7,
            9,
            3,
            9,
            9,
            10,
            3,
            4,
            1,
            10,
            8,
            10,
            1,
            8,
            10,
            9,
            8
        ],
        "poster": "MV5BMTAyNDU0NjY4NTheQTJeQWpwZ15BbWU2MDk4MTY2Nw@@._V1_SY256_SX175_AL_.jpg",
        "contentRating": "11",
        "duration": "PT179M",
        "releaseDate": "2002-12-18",
        "averageRating": 0,
        "originalTitle": "The Lord of the Rings: The Two Towers",
        "storyline": "While Frodo and Sam, now accompanied by a new guide, continue their hopeless journey towards the land of shadow to destroy the One Ring, each member of the broken fellowship plays their part in the battle against the evil wizard Saruman and his armies of Isengard.",
        "actors": [
            "Elijah Wood",
            "Ian McKellen",
            "Viggo Mortensen"
        ],
        "imdbRating": 8.7,
        "posterurl": "https://images-na.ssl-images-amazon.com/images/M/MV5BMTAyNDU0NjY4NTheQTJeQWpwZ15BbWU2MDk4MTY2Nw@@._V1_SY256_SX175_AL_.jpg",
        "isRated": false
    },
    {
        "id": 16,
        "title": "G\u00f6kboet",
        "year": "1975",
        "genres": [
            "Drama"
        ],
        "ratings": [
            2,
            8,
            4,
            8,
            7,
            9,
            2,
            8,
            5,
            9,
            3,
            5,
            6,
            8,
            7,
            9,
            2,
            7,
            9,
            9,
            7,
            3,
            7,
            8,
            7,
            1,
            10,
            10,
            3,
            3
        ],
        "poster": "MV5BZjA0OWVhOTAtYWQxNi00YzNhLWI4ZjYtNjFjZTEyYjJlNDVlL2ltYWdlL2ltYWdlXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_SY500_CR0,0,336,500_AL_.jpg",
        "contentRating": "15",
        "duration": "PT133M",
        "releaseDate": "1976-02-26",
        "averageRating": 0,
        "originalTitle": "One Flew Over the Cuckoo's Nest",
        "storyline": "McMurphy has a criminal past and has once again gotten himself into trouble and is sentenced by the court. To escape labor duties in prison, McMurphy pleads insanity and is sent to a ward for the mentally unstable. Once here, McMurphy both endures and stands witness to the abuse and degradation of the oppressive Nurse Ratched, who gains superiority and power through the flaws of the other inmates. McMurphy and the other inmates band together to make a rebellious stance against the atrocious Nurse.                Written by\nJacob Oberfrank",
        "actors": [
            "Jack Nicholson",
            "Louise Fletcher",
            "Michael Berryman"
        ],
        "imdbRating": 8.7,
        "posterurl": "https://images-na.ssl-images-amazon.com/images/M/MV5BZjA0OWVhOTAtYWQxNi00YzNhLWI4ZjYtNjFjZTEyYjJlNDVlL2ltYWdlL2ltYWdlXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_SY500_CR0,0,336,500_AL_.jpg",
        "isRated": false
    },
    {
        "id": 17,
        "title": "Maffiabr\u00f6der",
        "year": "1990",
        "genres": [
            "Biography",
            "Crime",
            "Drama"
        ],
        "ratings": [
            5,
            9,
            10,
            10,
            8,
            4,
            10,
            4,
            2,
            1,
            10,
            9,
            5,
            5,
            7,
            7,
            3,
            7,
            6,
            5,
            9,
            6,
            1,
            3,
            3,
            9,
            9,
            3,
            5,
            5
        ],
        "poster": "MV5BNThjMzczMjctZmIwOC00NTQ4LWJhZWItZDdhNTk5ZTdiMWFlXkEyXkFqcGdeQXVyNDYyMDk5MTU@._V1_SY500_CR0,0,334,500_AL_.jpg",
        "contentRating": "15",
        "duration": "PT146M",
        "releaseDate": "1990-09-14",
        "averageRating": 0,
        "originalTitle": "Goodfellas",
        "storyline": "Henry Hill might be a small time gangster, who may have taken part in a robbery with Jimmy Conway and Tommy De Vito, two other gangsters who might have set their sights a bit higher. His two partners could kill off everyone else involved in the robbery, and slowly start to think about climbing up through the hierarchy of the Mob. Henry, however, might be badly affected by his partners' success, but will he consider stooping low enough to bring about the downfall of Jimmy and Tommy?                Written by\nColin Tinto <cst@imdb.com>",
        "actors": [
            "Robert De Niro",
            "Ray Liotta",
            "Joe Pesci"
        ],
        "imdbRating": 8.7,
        "posterurl": "https://images-na.ssl-images-amazon.com/images/M/MV5BNThjMzczMjctZmIwOC00NTQ4LWJhZWItZDdhNTk5ZTdiMWFlXkEyXkFqcGdeQXVyNDYyMDk5MTU@._V1_SY500_CR0,0,334,500_AL_.jpg",
        "isRated": false
    },
    {
        "id": 18,
        "title": "Matrix",
        "year": "1999",
        "genres": [
            "Action",
            "Sci-Fi"
        ],
        "ratings": [
            10,
            10,
            5,
            1,
            8,
            8,
            10,
            9,
            6,
            2,
            1,
            9,
            3,
            1,
            5,
            1,
            8,
            5,
            8,
            8,
            5,
            7,
            6,
            5,
            8,
            6,
            3,
            6,
            6,
            10
        ],
        "poster": "MV5BNzQzOTk3OTAtNDQ0Zi00ZTVkLWI0MTEtMDllZjNkYzNjNTc4L2ltYWdlXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_SY500_CR0,0,332,500_AL_.jpg",
        "contentRating": "15",
        "duration": "PT136M",
        "releaseDate": "1999-07-14",
        "averageRating": 0,
        "originalTitle": "The Matrix",
        "storyline": "Thomas A. Anderson is a man living two lives. By day he is an average computer programmer and by night a hacker known as Neo. Neo has always questioned his reality, but the truth is far beyond his imagination. Neo finds himself targeted by the police when he is contacted by Morpheus, a legendary computer hacker branded a terrorist by the government. Morpheus awakens Neo to the real world, a ravaged wasteland where most of humanity have been captured by a race of machines that live off of the humans' body heat and electrochemical energy and who imprison their minds within an artificial reality known as the Matrix. As a rebel against the machines, Neo must return to the Matrix and confront the agents: super-powerful computer programs devoted to snuffing out Neo and the entire human rebellion.                Written by\nredcommander27",
        "actors": [
            "Keanu Reeves",
            "Laurence Fishburne",
            "Carrie-Anne Moss"
        ],
        "imdbRating": 8.7,
        "posterurl": "https://images-na.ssl-images-amazon.com/images/M/MV5BNzQzOTk3OTAtNDQ0Zi00ZTVkLWI0MTEtMDllZjNkYzNjNTc4L2ltYWdlXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_SY500_CR0,0,332,500_AL_.jpg",
        "isRated": false
    },
    {
        "id": 19,
        "title": "De sju samurajerna",
        "year": "1954",
        "genres": [
            "Adventure",
            "Drama"
        ],
        "ratings": [
            1,
            9,
            9,
            6,
            6,
            1,
            3,
            1,
            6,
            1,
            9,
            6,
            1,
            7,
            7,
            10,
            5,
            3,
            9,
            4,
            6,
            6,
            9,
            10,
            6,
            10,
            7,
            1,
            6,
            10
        ],
        "poster": "MV5BMTc5MDY1MjU5MF5BMl5BanBnXkFtZTgwNDM2OTE4MzE@._V1_SY500_CR0,0,356,500_AL_.jpg",
        "contentRating": "15",
        "duration": "PT207M",
        "releaseDate": "1965-09-20",
        "averageRating": 0,
        "originalTitle": "Shichinin no samurai",
        "storyline": "A veteran samurai, who has fallen on hard times, answers a village's request for protection from bandits. He gathers 6 other samurai to help him, and they teach the townspeople how to defend themselves, and they supply the samurai with three small meals a day. The film culminates in a giant battle when 40 bandits attack the village.                Written by\nColin Tinto <cst@imdb.com>",
        "actors": [
            "Toshir\u00f4 Mifune",
            "Takashi Shimura",
            "Keiko Tsushima"
        ],
        "imdbRating": 8.7,
        "posterurl": "https://images-na.ssl-images-amazon.com/images/M/MV5BMTc5MDY1MjU5MF5BMl5BanBnXkFtZTgwNDM2OTE4MzE@._V1_SY500_CR0,0,356,500_AL_.jpg",
        "isRated": false
    },
    {
        "id": 20,
        "title": "Stj\u00e4rnornas krig",
        "year": "1977",
        "genres": [
            "Action",
            "Adventure",
            "Fantasy"
        ],
        "ratings": [
            6,
            3,
            3,
            4,
            2,
            10,
            7,
            4,
            1,
            5,
            7,
            8,
            6,
            4,
            2,
            7,
            9,
            3,
            4,
            4,
            7,
            7,
            7,
            4,
            8,
            2,
            7,
            5,
            2,
            9
        ],
        "poster": "MV5BYzQ2OTk4N2QtOGQwNy00MmI3LWEwNmEtOTk0OTY3NDk2MGJkL2ltYWdlL2ltYWdlXkEyXkFqcGdeQXVyNjc1NTYyMjg@._V1_SY500_CR0,0,332,500_AL_.jpg",
        "contentRating": "11",
        "duration": "PT121M",
        "releaseDate": "1977-12-16",
        "averageRating": 0,
        "originalTitle": "Star Wars",
        "storyline": "The Imperial Forces, under orders from cruel Darth Vader, hold Princess Leia hostage in their efforts to quell the rebellion against the Galactic Empire. Luke Skywalker and Han Solo, captain of the Millennium Falcon, work together with the companionable droid duo R2-D2 and C-3PO to rescue the beautiful princess, help the Rebel Alliance and restore freedom and justice to the Galaxy.                Written by\nJwelch5742",
        "actors": [
            "Mark Hamill",
            "Harrison Ford",
            "Carrie Fisher"
        ],
        "imdbRating": 8.7,
        "posterurl": "https://images-na.ssl-images-amazon.com/images/M/MV5BYzQ2OTk4N2QtOGQwNy00MmI3LWEwNmEtOTk0OTY3NDk2MGJkL2ltYWdlL2ltYWdlXkEyXkFqcGdeQXVyNjc1NTYyMjg@._V1_SY500_CR0,0,332,500_AL_.jpg",
        "isRated": false
    },
    {
        "id": 21,
        "title": "Guds stad",
        "year": "2002",
        "genres": [
            "Crime",
            "Drama"
        ],
        "ratings": [
            1,
            2,
            5,
            10,
            1,
            2,
            6,
            10,
            2,
            9,
            7,
            9,
            7,
            9,
            4,
            8,
            7,
            7,
            7,
            7,
            10,
            9,
            9,
            2,
            6,
            6,
            6,
            2,
            1,
            8
        ],
        "poster": "MV5BMjA4ODQ3ODkzNV5BMl5BanBnXkFtZTYwOTc4NDI3._V1_SX200_CR0,0,200,296_AL_.jpg",
        "contentRating": "15",
        "duration": "PT130M",
        "releaseDate": "2003-10-17",
        "averageRating": 0,
        "originalTitle": "Cidade de Deus",
        "storyline": "Brazil, 1960s, City of God. The Tender Trio robs motels and gas trucks. Younger kids watch and learn well...too well. 1970s: Li'l Z\u00e9 has prospered very well and owns the city. He causes violence and fear as he wipes out rival gangs without mercy. His best friend Ben\u00e9 is the only one to keep him on the good side of sanity. Rocket has watched these two gain power for years, and he wants no part of it. Yet he keeps getting swept up in the madness. All he wants to do is take pictures. 1980s: Things are out of control between the last two remaining gangs...will it ever end? Welcome to the City of God.                Written by\nJeff Mellinger <jeffmellinger@astound.net>",
        "actors": [
            "Alexandre Rodrigues",
            "Matheus Nachtergaele",
            "Leandro Firmino"
        ],
        "imdbRating": 8.7,
        "posterurl": "https://images-na.ssl-images-amazon.com/images/M/MV5BMjA4ODQ3ODkzNV5BMl5BanBnXkFtZTYwOTc4NDI3._V1_SX200_CR0,0,200,296_AL_.jpg",
        "isRated": false
    },
    {
        "id": 22,
        "title": "Seven",
        "year": "1995",
        "genres": [
            "Crime",
            "Drama",
            "Mystery"
        ],
        "ratings": [
            2,
            5,
            2,
            3,
            9,
            1,
            8,
            2,
            3,
            4,
            10,
            7,
            9,
            7,
            8,
            2,
            5,
            6,
            1,
            5,
            1,
            2,
            10,
            5,
            1,
            7,
            4,
            8,
            9,
            4
        ],
        "poster": "MV5BOTUwODM5MTctZjczMi00OTk4LTg3NWUtNmVhMTAzNTNjYjcyXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_SY500_CR0,0,319,500_AL_.jpg",
        "contentRating": "15",
        "duration": "PT127M",
        "releaseDate": "1995-12-25",
        "averageRating": 0,
        "originalTitle": "Se7en",
        "storyline": "A film about two homicide detectives' (Morgan Freeman and (Brad Pitt desperate hunt for a serial killer who justifies his crimes as absolution for the world's ignorance of the Seven Deadly Sins. The movie takes us from the tortured remains of one victim to the next as the sociopathic \"John Doe\" (Kevin Spacey) sermonizes to Detectives Somerset and Mills -- one sin at a time. The sin of Gluttony comes first and the murderer's terrible capacity is graphically demonstrated in the dark and subdued tones characteristic of film noir. The seasoned and cultured but jaded Somerset researches the Seven Deadly Sins in an effort to understand the killer's modus operandi while the bright but green and impulsive Detective Mills (Pitt) scoffs at his efforts to get inside the mind of a killer...                Written by\nMark Fleetwood <mfleetwo@mail.coin.missouri.edu>",
        "actors": [
            "Morgan Freeman",
            "Brad Pitt",
            "Kevin Spacey"
        ],
        "imdbRating": 8.6,
        "posterurl": "https://images-na.ssl-images-amazon.com/images/M/MV5BOTUwODM5MTctZjczMi00OTk4LTg3NWUtNmVhMTAzNTNjYjcyXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_SY500_CR0,0,319,500_AL_.jpg",
        "isRated": false
    },
    {
        "id": 23,
        "title": "N\u00e4r lammen tystnar",
        "year": "1991",
        "genres": [
            "Crime",
            "Drama",
            "Thriller"
        ],
        "ratings": [
            6,
            10,
            7,
            5,
            10,
            10,
            2,
            3,
            7,
            7,
            9,
            10,
            1,
            4,
            1,
            9,
            3,
            1,
            9,
            4,
            2,
            6,
            6,
            1,
            9,
            8,
            7,
            9,
            2,
            10
        ],
        "poster": "MV5BMTQ2NzkzMDI4OF5BMl5BanBnXkFtZTcwMDA0NzE1NA@@._V1_SY500_CR0,0,333,500_AL_.jpg",
        "contentRating": "15",
        "duration": "PT118M",
        "releaseDate": "1991-03-22",
        "averageRating": 0,
        "originalTitle": "The Silence of the Lambs",
        "storyline": "FBI trainee Clarice Starling works hard to advance her career, including trying to hide or put behind her West Virginia roots, of which if some knew would automatically classify her as being backward or white trash. After graduation, she aspires to work in the agency's Behavioral Science Unit under the leadership of Jack Crawford. While she is still a trainee, Crawford does ask her to question Dr. Hannibal Lecter, a psychiatrist imprisoned thus far for eight years in maximum security isolation for being a serial killer, he who cannibalized his victims. Clarice is able to figure out the assignment is to pick Lecter's brains to help them solve another serial murder case, that of someone coined by the media as Buffalo Bill who has so far killed five victims, all located in the eastern US, all young women who are slightly overweight especially around the hips, all who were drowned in natural bodies of water, and all who were stripped of large swaths of skin. She also figures that Crawford...                Written by\nHuggo",
        "actors": [
            "Jodie Foster",
            "Anthony Hopkins",
            "Lawrence A. Bonney"
        ],
        "imdbRating": 8.6,
        "posterurl": "https://images-na.ssl-images-amazon.com/images/M/MV5BMTQ2NzkzMDI4OF5BMl5BanBnXkFtZTcwMDA0NzE1NA@@._V1_SY500_CR0,0,333,500_AL_.jpg",
        "isRated": false
    },
    {
        "id": 24,
        "title": "Livet \u00e4r underbart",
        "year": "1946",
        "genres": [
            "Drama",
            "Family",
            "Fantasy"
        ],
        "ratings": [
            1,
            4,
            2,
            1,
            7,
            1,
            9,
            8,
            4,
            9,
            5,
            7,
            7,
            7,
            10,
            9,
            9,
            1,
            4,
            10,
            3,
            6,
            10,
            7,
            3,
            2,
            2,
            10,
            2,
            2
        ],
        "poster": "MV5BMTMzMzY5NDc4M15BMl5BanBnXkFtZTcwMzc4NjIxNw@@._V1_SY500_CR0,0,334,500_AL_.jpg",
        "contentRating": "15",
        "duration": "PT130M",
        "releaseDate": "1947-08-04",
        "averageRating": 0,
        "originalTitle": "It's a Wonderful Life",
        "storyline": "George Bailey has spent his entire life giving of himself to the people of Bedford Falls. He has always longed to travel but never had the opportunity in order to prevent rich skinflint Mr. Potter from taking over the entire town. All that prevents him from doing so is George's modest building and loan company, which was founded by his generous father. But on Christmas Eve, George's Uncle Billy loses the business's $8,000 while intending to deposit it in the bank. Potter finds the misplaced money and hides it from Billy. When the bank examiner discovers the shortage later that night, George realizes that he will be held responsible and sent to jail and the company will collapse, finally allowing Potter to take over the town. Thinking of his wife, their young children, and others he loves will be better off with him dead, he contemplates suicide. But the prayers of his loved ones result in a gentle angel named Clarence coming to earth to help George, with the promise of earning his ...                Written by\nalfiehitchie",
        "actors": [
            "James Stewart",
            "Donna Reed",
            "Lionel Barrymore"
        ],
        "imdbRating": 8.6,
        "posterurl": "https://images-na.ssl-images-amazon.com/images/M/MV5BMTMzMzY5NDc4M15BMl5BanBnXkFtZTcwMzc4NjIxNw@@._V1_SY500_CR0,0,334,500_AL_.jpg",
        "isRated": false
    },
    {
        "id": 25,
        "title": "De misst\u00e4nkta",
        "year": "1995",
        "genres": [
            "Crime",
            "Drama",
            "Mystery"
        ],
        "ratings": [
            5,
            8,
            6,
            6,
            4,
            2,
            1,
            9,
            6,
            2,
            5,
            1,
            6,
            10,
            1,
            8,
            7,
            6,
            10,
            3,
            7,
            7,
            5,
            1,
            8,
            8,
            6,
            4,
            10,
            9
        ],
        "poster": "MV5BMzI1MjI5MDQyOV5BMl5BanBnXkFtZTcwNzE4Mjg3NA@@._V1_SY500_CR0,0,333,500_AL_.jpg",
        "contentRating": "15",
        "duration": "PT106M",
        "releaseDate": "1995-11-03",
        "averageRating": 0,
        "originalTitle": "The Usual Suspects",
        "storyline": "Following a truck hijack in New York, five conmen are arrested and brought together for questioning. As none of them are guilty, they plan a revenge operation against the police. The operation goes well, but then the influence of a legendary mastermind criminal called Keyser S\u00f6ze is felt. It becomes clear that each one of them has wronged S\u00f6ze at some point and must pay back now. The payback job leaves 27 men dead in a boat explosion, but the real question arises now: Who actually is Keyser S\u00f6ze?                Written by\nSoumitra",
        "actors": [
            "Kevin Spacey",
            "Gabriel Byrne",
            "Chazz Palminteri"
        ],
        "imdbRating": 8.6,
        "posterurl": "https://images-na.ssl-images-amazon.com/images/M/MV5BMzI1MjI5MDQyOV5BMl5BanBnXkFtZTcwNzE4Mjg3NA@@._V1_SY500_CR0,0,333,500_AL_.jpg",
        "isRated": false
    }
]
const getMovies = () => {
      return movies;
}

const getGenres= ()=> {
    const genre = new Set();
    movies.forEach(movie => {
        if(Array.isArray(movie.genres)) movie.genres.forEach(g => genre.add(g))
    });

    const convertedArray = Array.from(genre);
    return convertedArray.map((g, idx) => ({ id: idx, name: g}))
}

export {
    getMovies,
    getGenres

}
